USE DATABASE NONPROD_FRAUD;
USE SCHEMA STAGE;

TRUNCATE TABLE THREATMATRIX_EVENTS_STAGE;

INSERT INTO THREATMATRIX_EVENTS_STAGE
SELECT
    EVENT_ID,
    EVENT_DATA:customerId::STRING,
    EVENT_DATA:customerName::STRING,
    EVENT_DATA:email::STRING,
    EVENT_DATA:country::STRING,
    EVENT_DATA:device::STRING,
    EVENT_DATA:riskScore::NUMBER,
    EVENT_DATA:status::STRING,
    EVENT_TIME,
    LOAD_TS
FROM NONPROD_FRAUD.RAW.THREATMATRIX_EVENTS;