USE DATABASE NONPROD_FRAUD;
USE SCHEMA MART;

CREATE OR REPLACE TABLE FRAUD_SUMMARY
(
    COUNTRY STRING,
    RISK_LEVEL STRING,
    TOTAL_EVENTS NUMBER,
    BLOCKED_EVENTS NUMBER,
    SUCCESS_EVENTS NUMBER,
    LOAD_TS TIMESTAMP_NTZ
);