USE DATABASE NONPROD_FRAUD;
USE SCHEMA MART;

INSERT INTO FRAUD_SUMMARY
SELECT
    COUNTRY,
    RISK_LEVEL,
    COUNT(*) AS TOTAL_EVENTS,

    SUM(
        CASE
            WHEN STATUS = 'BLOCKED' THEN 1
            ELSE 0
        END
    ) AS BLOCKED_EVENTS,

    SUM(
        CASE
            WHEN STATUS = 'SUCCESS' THEN 1
            ELSE 0
        END
    ) AS SUCCESS_EVENTS,

    CURRENT_TIMESTAMP()

FROM NONPROD_FRAUD.INTERMEDIATE.THREATMATRIX_EVENTS_INT

GROUP BY
    COUNTRY,
    RISK_LEVEL;