USE WAREHOUSE NONPROD_WH;
USE DATABASE NONPROD_FRAUD;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE THREATMATRIX_EVENTS (

    EVENT_ID STRING,

    EVENT_SOURCE STRING,

    EVENT_TYPE STRING,

    EVENT_TIME TIMESTAMP_NTZ,

    EVENT_DATA VARIANT,

    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);