SELECT
    EVENT_ID,
    EVENT_SOURCE,
    EVENT_TYPE,
    EVENT_TIME,
    EVENT_DATA,
    EVENT_DATA:customerId::STRING AS CUSTOMER_ID,
    EVENT_DATA:country::STRING AS COUNTRY,
    EVENT_DATA:riskScore::NUMBER AS RISK_SCORE,
    LOAD_TS
FROM THREATMATRIX_EVENTS;