-- ===================================================
-- Project : Threat Matrix Monitoring
-- Purpose : Create Snowflake Environment
-- ===================================================

CREATE WAREHOUSE IF NOT EXISTS NONPROD_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS NONPROD_FRAUD;

CREATE SCHEMA IF NOT EXISTS NONPROD_FRAUD.RAW;
CREATE SCHEMA IF NOT EXISTS NONPROD_FRAUD.STAGE;
CREATE SCHEMA IF NOT EXISTS NONPROD_FRAUD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NONPROD_FRAUD.MART;